#!/bin/bash
#
# ~/bin/dwm-start
#

exec dwm &
exec /home/asterius/.config/scripts/dwm-statusbar

#while true; do
    # Log stderror to a file
#    dwm 2>  $HOME/.logs/dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
#done

