#!/bin/bash
#
# Script to fetch mail automatically (with crontab) every minute.
# Author: Asterius

# kill offlineimap if active, sometimes it hangs
	offlineimap -o -u quiet &	

	case $imapactive in
		'1')
 		killall offlineimap && sleep 1
	;;
	esac
